gn check_http__cas_login_service_http_3A_2F_2Fuplace.utah.edu_2F ulogin.utah.eduPass -remove -no_reload
gn check_http__wfc_logon www.kronos.utah.edu Pass -remove -no_reload
gn check_http__acs_ www.acs.utah.edu  Pass -remove -no_reload
gn check_http__netdisco_login.html_done__2Fnetdisco_2Findex.html smgnag3.med.utah.edu  Pass -remove -no_reload
gn check_http__academic-calendars_index.php registrar.utah.edu Pass -remove -no_reload
gn check_http__dana-na_auth_url_7_welcome.cgi myvpn.med.utah.edu Pass -remove -no_reload
gn check_http__activityreport_login.hml faculty.utah.edu Pass -remove -no_reload
gn appinfo_cmd_prsr_epicintconcptest.med.utah.edu localhost Pass -remove -no_reload
gn check_http__wfc_logon www.kronos.utah.edu Pass -remove -no_reload
gn check_http__a-z_ www.utah.edu Pass -remove -no_reload
gn check_http__radiology_ medicine.utah.edu Pass -remove -no_reload
gn check_http__poison_ uuhsc.utah.edu Pass -remove -no_reload
gn check_http__uofu_acs_uupasswd_ www.acs.utah.edu Pass -remove -no_reload
gn check_http__acs_ www.acs.utah.edu Pass -remove -no_reload
gn check_http__users_login umcfileshare.utah.edu Pass -remove -no_reload
gn check_http__uofu_misc_uWho_basic.hml people.utah.edu Pass -remove -no_reload
gn check_http__a-z_ www.utah.edu Pass -remove -no_reload
gn check_http__netdisco_login.html_done__2Fnetdisco_2Findex.html smgnag3.med.utah.edu Pass -remove -no_reload
gn check_http__academic-calendars_index.php registrar.utah.edu Pass -remove -no_reload
gn check_http__wws_ sympa.csbs.utah.edu Pass -remove -no_reload
gn check_http__portal_site_myutah_template.LOGIN_action.process_ my.utah.edu Pass -remove -no_reload
gn check_http__cas_login go.utah.edu Pass -remove -no_reload
gn check_http__income_ fbs.admin.utah.edu Pass -remove -no_reload
gn check_http__activityreport_login.hml faculty.utah.edu Pass -remove -no_reload
gn check_http__dana-na_auth_url_7_welcome.cgi myvpn.med.utah.edu Pass -remove -no_reload
gn check_http__wfc_logon www.kronos.utah.edu Pass -remove -no_reload
gn check_http__wfc_applications_wtk_html_ess_logon.jsp www.kronos.utah.edu Pass -remove -no_reload
gn check_http__nidtools.epl unid.utah.edu Pass -remove -no_reload
gn icmp_ping_alive epictstctx11.med.utah.edu Pass -remove -no_reload
gn cpu_activity_CPU0 epictstctx11.med.utah.edu Pass -remove -no_reload
gn disk_space_W: epictstctx11.med.utah.edu Pass -remove -no_reload
gn icmp_ping_alive ddr1-2-komas-dc-med_vlan340-122.1.med.utah.edu Pass -remove -no_reload
